server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddplatform?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      host: localhost
      port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
oss:
  accessKey: P63Uq30HFdyypBodfr6GatBBKvO16o0nxiGLasQU
  secretKey: w0ip73RotUDhWg03ZYXQImBuLudlvpbh-Ccuyyi7
  bucket: riptide-platform
  zone: huadong
  domain: rsaaqbr24.bkt.clouddn.com